
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 17 20:41:12 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAP = 25;
  public static final int LTE = 43;
  public static final int LBRACKET = 34;
  public static final int CHAR = 48;
  public static final int CONST = 17;
  public static final int LPAREN = 11;
  public static final int SEMI = 8;
  public static final int CONTINUE = 21;
  public static final int MINUS = 4;
  public static final int RPAREN = 6;
  public static final int AND = 32;
  public static final int LT = 42;
  public static final int OR = 31;
  public static final int BOOL = 49;
  public static final int COMMA = 13;
  public static final int CLASS = 18;
  public static final int INC = 26;
  public static final int DIV = 29;
  public static final int PLUS = 3;
  public static final int IF = 10;
  public static final int THIS = 36;
  public static final int DOT = 33;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int RBRACKET = 35;
  public static final int EQUAL = 7;
  public static final int NEW = 37;
  public static final int error = 1;
  public static final int MUL = 28;
  public static final int NUMBER = 46;
  public static final int MOD = 30;
  public static final int NEQ = 39;
  public static final int IDENT = 47;
  public static final int BREAK = 20;
  public static final int VOID = 16;
  public static final int EQ = 38;
  public static final int GTE = 41;
  public static final int FOREACH = 24;
  public static final int LBRACE = 12;
  public static final int ELSE = 2;
  public static final int ENUM = 44;
  public static final int READ = 22;
  public static final int WHILE = 23;
  public static final int RBRACE = 5;
  public static final int EXTENDS = 19;
  public static final int PROG = 14;
  public static final int DEC = 27;
  public static final int GT = 40;
  public static final int DO = 45;
  public static final int PRINT = 15;
}

